server:
  port: 8222

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**

        - id: project-service-public-verify
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/projects/invitations/verify
          filters:
            - RemoveRequestHeader=Authorization

        - id: project-service-invitations-accept
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/projects/invitations/accept

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/projects/**

        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/v1/tasks/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost"
              - "${FRONTEND_URL:http://localhost}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: ${JWT_SECRET}